### ISSUE TITLE
Submodule recursion

### ISSUE THREAD

**Issue by viharm** [Andr3as/Codiad-CodeGit#20]
Is there support for recursively cloning submodules? If so, how can I do this?

**Comment by Andr3as** [comment]
No currently not. But it's maybe a thing for a future release.

**Comment by viharm** [comment]
Hi Andr3as, is this on the roadmap yet?

**Comment by viharm** [comment]
Hi Andr3as, any updates on this yet?
I have found a standalone git client, and am currently using it alongside Codiad

https://github.com/FredrikNoren/ungit

**Comment by Andr3as** [comment]
Yes, it's definitely on the list

**Comment by Andr3as** [comment]
Check the PR for further details #43

**Comment by Andr3as** [comment]
Merged with f4f1c71
