### ISSUE TITLE
Bad commit messages encoding/escaping

### ISSUE THREAD

**Issue by Mageti** [Andr3as/Codiad-CodeGit#32]
Hello,
I've been using CodeGit on Codiad for a moment now, and I find it so useful, thank for that.
But I found a problem : commit messages are bad encoded/escaped. As I am french, using other characters than pure ASCII, it is a problem to me. Here is an example : 
I enter this commit message : "Correction d'une traduction", in git log, the message become "Correction d\'une traduction". Or "Amlioration de la rcupration" registered instead of "Amélioration de la récupération".
Here is a snippet of my git log (see the special characters "à" and "é" in the commit made through commandline) : 
```
commit bd9f5b48a94578eba288ae23ee9c3b8b975c2683
Author: Myself through commandline <myself@example.net>
Date:   Wed Dec 30 22:26:27 2015 +0100

    Journaux à intégrer : USA

commit 52991bc5a76d9e02ba120f2d1826c85aa8d45ec0
Author: Myself through Codiad CodeGit <myself@example.net>
Date:   Wed Dec 30 13:58:57 2015 +0100

    Correction d\'une traduction

commit d1db5e3dcf4c4252f0b6a04fb5b4f994100af55d
Author: Myself through Codiad CodeGit <myself@example.net>
Date:   Wed Dec 30 13:40:59 2015 +0100

    Amlioration de la rcupration des articles
```
Hope you could do something for me :)

**Comment by Andr3as** [comment]
Sorry, it's not possible. The [escaping](https://github.com/Andr3as/Codiad-CodeGit/blob/master/class.git.php#L514) prevents code injection. The easiest way to do this is by using a php method. Unless you know a way to change this…

**Comment by Mageti** [comment]
as soon as I have some time to do it, I may test this : http://php.net/manual/fr/function.escapeshellarg.php#99213

**Comment by Andr3as** [comment]
Update: see #48, this may help you.

**Comment by Mageti** [comment]
@Andr3as Great, thanks ! works for me :+1:
