### ISSUE TITLE
missing authentication when ssh into git repository

### ISSUE THREAD

**Issue by mcinano** [Andr3as/Codiad-CodeGit#34]
Hi

I want to sync a git reository residing under something like:
`gituser@localhost:/home/gituser/myrepo`
Codiad stalls, when trying to clone this way. I would expect a question for password input.
`ps aux` shows waiting ssh connection processes. I assume it is waiting for a password.

Should this work? Is it me, ssh'ing to localhost? Am I missing soem configuration?

**Comment by mcinano** [comment]
In addition i tired to to clone via codiad terminal. Maybe this is helpful?
```
Cloning into 'myrepo'...
Could not create directory '/var/www/.ssh'.
Host key verification failed.
fatal: The remote end hung up unexpectedly
```

`/var/www/` is the home directory of www-data, the process owner of apache providing codiad i suppose.
I can't

**Comment by Andr3as** [comment]
Your problem bassed on two problems:

1. The older version of CodeGit didn't support the different password question output for ssh - I fixed this
2. You have to add your servers host key for the www-data user
