### ISSUE TITLE
Bitbucket Support

### ISSUE THREAD

**Issue by mdinesh-kumar** [Andr3as/Codiad-CodeGit#40]
Hi I tried to pull existing records from bitbucket but its throwing error. Whether it will be supported?

**Comment by Andr3as** [comment]
Theoretically there is no limitation on a specific git provider. Bitbucket works as I tested it today. Have you some details of your error?

**Comment by mdinesh-kumar** [comment]
How to access private bitbucket?

**Comment by mdinesh-kumar** [comment]
![screenshot from 2016-10-24 12-36-40](https://cloud.githubusercontent.com/assets/22271175/19637098/def87eba-99ea-11e6-8dc2-8fb270d6c52f.png)
You can see error as "dose not appear to be git repository" it is private git repository for which i should enter user name and password usually

**Comment by Andr3as** [comment]
This looks like an error of git itself. Do you tested it over a console or so?
Do you pull over ssh or https?

Stupid question, but are you sure your remote url is correct and it's a git repo (BitBucket provides Mercurial repos too).

**Comment by viharm** [comment]
Bitbucket is a bit weird as the HTTP clone URL it provides has the username embedded. E.g., `https://viharm@bitbucket.org/viharm/xatafaceldapauth.git`.  This is a non-standard Git URL. Just remove the username and the "@" symbol and try again. The following should work... 
`https://bitbucket.org/viharm/xatafaceldapauth.git`

**Comment by viharm** [comment]
CodeGit will prompt for a username and password for private repositories.

**Comment by Andr3as** [comment]
I tested it `https://Andr3as@bitbucket.org/Andr3as/codegit.git` several times without any problems. Please reopen if required
