### ISSUE TITLE
how do i setup pexpect to use with codiad

### ISSUE THREAD

**Issue by jappyjan** [Andr3as/Codiad-CodeGit#47]
How do i setup/configure codiad to use pexpect for git authentication?
i could only find instructions on how to install it...

**Comment by Andr3as** [comment]
Sorry for my late response.

It should work with the following config:
Comment this line out: [Line 3 in config.php](https://github.com/Andr3as/Codiad-CodeGit/blob/master/config.php#L3)
and remove the comment from this one: [Line 5 in config.php](https://github.com/Andr3as/Codiad-CodeGit/blob/master/config.php#L5)

**Comment by Andr3as** [comment]
Please reopen if required
