### ISSUE TITLE
Corrupted git strings

### ISSUE THREAD

**Issue by waclaw66** [Andr3as/Codiad-CodeGit#50]
Hi.
Git user settings is stored in data/config/git.{user}.php file. My user name is stored escaped like `V\u00e1clav Nov\u00e1\u010dek` which means `Václav Nováček` and it is correctly set and visible in CodeGit user settings window. When user settings is used for commit, following command (class.git.php:532):
`$result = $this->executeCommand('git config user.name "' . $username . '"');`
is executed and git stores corrupted name `Vclav Novek` without middle-european characters.
The same applies also for commit comments.

**Comment by Andr3as** [comment]
See #48, this may help you.

**Comment by Andr3as** [comment]
Please reopen if required
