### ISSUE TITLE
Git crashes ide

### ISSUE THREAD

**Issue by jappyjan** [Andr3as/Codiad-CodeGit#51]
I had to reset my remote git repository.
Afterwards i wasn't able to use codeGit anymore.
The remote repository didn't change at all, and works fine when trying to push/pull from another PC...
As soon as i try to pul from it via CodeGit i can't reach the ide anymore... it just crashes...
I'm not using ssh keys and i have configured expect correctly (worked before), i tryed to use a .netrc file as well...

**Comment by Andr3as** [comment]
Sry, I am not able to reproduce your problem. Which size does your repo have and how long does the cloning normally takes? There is a three minute timelimit in `expect.sh`.
