### ISSUE TITLE
Permission change on git push

### ISSUE THREAD

**Issue by jakadinho** [Andr3as/Codiad-CodeGit#54]
My files have 640 permission on local machine. When i push them to git and then pull to production machine it changes to 644. For some reason my shared hosting server then gives Internal Server Error. When permission is changed back to 640 it works fine.

I havent have this problem using command line. I really like Codiad and your plugin which i discovered yesterday. I would love the option that pushed files would have the same permissions as local files.

**Comment by jakadinho** [comment]
Never mind got it working.
Its actualy connected to other plugin. If other might have same problem, the solution is to edit Codiad-CompletePlus-master/extensions/snippets/php.json

**Comment by Andr3as** [comment]
Sry, I don't understand your solution. Nevertheless if it works for you, I'll close this issue.
