### ISSUE TITLE
Error:  "Warning: session_start(): Cannot send session cache limiter"

### ISSUE THREAD

**Issue by seanvree** [Andr3as/Codiad-CodeGit#57]
OS:  Windows 10E 1703 X64
Codiad ver:  v.2.8.4
PHP: 7.1.7 x64

Getting this error when I go to the settings form in CodeGIT:
```

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at C:\inetpub\wwwroot\Codiad\plugins\Codiad-CodeGit-master\dialog.php:1) in C:\inetpub\wwwroot\Codiad\common.php on line 88
```

I'm also unable to push/pull although, I'm not sure if that's related. 

I can use GIT PUSH/PULL from the terminal, however. 

I tried to apply this fix below, but didn't help:

https://github.com/Codiad/Codiad/issues/170

Screenshot:

![codiadgit](https://user-images.githubusercontent.com/8906637/29168526-19f4e2d8-7d84-11e7-963a-556fc9442638.png)

**Comment by Andr3as** [comment]
I'm not able to reproduce your issue. Nevertheless I hope [branch 57](https://github.com/Andr3as/Codiad-CodeGit/tree/issue_57) fixes it. Could you please test it and if it works I'll merge it into master.

**Comment by seanvree** [comment]
@Andr3as 

Yup! That worked!

Still not able to push or pull, but I'll open another issue for that as this doesn't seem to be related. 

![image](https://user-images.githubusercontent.com/8906637/29174819-4dc233aa-7d9c-11e7-9ca2-b3d613ebf513.png)
